import Link from 'next/link';
import { siteConfig } from '@/lib/site-config';

export const metadata = {
  title: 'Terms of Use',
  description: `Terms of Use for ${siteConfig.name}.`,
  alternates: { canonical: '/terms' },
};

const LAST_UPDATED = 'January 2026';

export default function TermsPage() {
  return (
    <main id="main">
      <section className="page-hero">
        <div className="container">
          <span className="eyebrow">📄 Legal</span>
          <h1>Terms of Use</h1>
          <p className="lead">Last updated: {LAST_UPDATED}</p>
        </div>
      </section>

      <section style={{ paddingTop: 0 }}>
        <div className="container">
          <div className="content-card prose">
            <h2>1. Acceptance of terms</h2>
            <p>
              By using {siteConfig.name} (&quot;the site&quot;), you agree to these Terms
              of Service. If you do not agree, please do not use the site.
            </p>

            <h2>2. The service</h2>
            <p>
              {siteConfig.name} provides a free, browser-based color analysis tool that
              estimates a &quot;seasonal&quot; color palette from a photo you provide, plus
              related tools (a color harmony generator and a garment recolor preview). The
              service is provided free of charge and requires no account.
            </p>

            <h2>3. Not professional advice</h2>
            <p>
              Results are generated by an automated, simplified color-theory heuristic and
              are provided for general informational and entertainment purposes only. They
              are not a substitute for advice from a professional colorist, stylist,
              dermatologist, or any other qualified professional. We make no guarantee
              about the accuracy of any result.
            </p>

            <h2>4. Your content</h2>
            <p>
              Photos you use with the tool are processed locally in your browser and are
              never transmitted to us — see our <Link href="/privacy-policy">Privacy
              Policy</Link> for details. You are responsible for only uploading photos you
              have the right to use, and for not using the tool with photos of other
              people without their consent.
            </p>

            <h2>5. Acceptable use</h2>
            <p>
              You agree not to misuse the site — including attempting to disrupt its
              operation, reverse engineer it for malicious purposes, or use it in any way
              that violates applicable law.
            </p>

            <h2>6. Intellectual property</h2>
            <p>
              The site&apos;s design, code, articles and branding are the property of{' '}
              {siteConfig.name} unless otherwise noted, and may not be reproduced without
              permission.
            </p>

            <h2>7. Third-party advertising</h2>
            <p>
              This site may display third-party advertising, including through Google
              AdSense. We are not responsible for the content of third-party
              advertisements or the sites they link to.
            </p>

            <h2>8. Disclaimer of warranties</h2>
            <p>
              The site is provided &quot;as is&quot; and &quot;as available,&quot; without
              warranties of any kind, express or implied, including but not limited to
              accuracy, reliability, or fitness for a particular purpose.
            </p>

            <h2>9. Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, {siteConfig.name} shall not be
              liable for any indirect, incidental, or consequential damages arising from
              your use of the site.
            </p>

            <h2>10. Changes to these terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the site after
              changes are posted constitutes acceptance of the revised Terms.
            </p>

            <h2>11. Contact</h2>
            <p>
              Questions about these Terms can be sent to{' '}
              <a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</a>.
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}
